export const FORMULARIO_MOSTRAR = "FORMULARIO_MOSTRAR";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";

export const TAREA_PROYECTO = "TAREA_PROYECTO";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const CAMBIAR_ESTADO = "CAMBIAR_ESTADO";
export const GUARDAR_TAREA = "GUARDAR_TAREA";
export const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA";
